branches:
  only:
    - "master"
    - "dev"
language: node_js
node_js:
  - "10"
services:
  - xvfb
addons:
  firefox: "latest"
before_script:
  - "export DISPLAY=:99.0"
script:
  gulp test --browsers Firefox
