# Test against the latest version of this Node.js version
environment:
  matrix:
    # first group
    - MAPTALKS_BROWSERS: IE
    # second group
    # - MAPTALKS_BROWSERS: IE10
    # - MAPTALKS_BROWSERS: IE9
# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node 6
  # install gulp globally
  - npm install gulp -g
  - npm i -g increase-memory-limit
  - increase-memory-limit
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run pretest
  - npm run testIE


matrix:
  fast_finish: true

# Don't actually build.
build: off

# https://github.com/appveyor/ci/issues/882
skip_branch_with_pr: true
